### ISSUE TITLE
Getting a meeting to work?

### ISSUE THREAD

**Issue by thelanj** [michaelbourne/gravity-forms-zoom-webinar-registration#1]
So excited that you made this!

However, I can't see to get this to work for normal meeting registration (non webinars).  Is there anything special i need to do to get that working?  I setup my JWT app, put in the api info, and put in the meeting ID to the feed but it doesn't seem to be sending any info to zoom.

**Comment by thelanj** [comment]
Nevermind, for some reason re-adding the API key seems to have done the trick.

**Comment by michaelbourne** [comment]
Glad you got it sorted. Not sure what may have caused that, but if it happens again, let me know.

Cheers.
