### ISSUE TITLE
Set type in Composer configuration to install in proper location

### ISSUE THREAD

**Issue by claytoncollie** [michaelbourne/gravity-forms-zoom-webinar-registration#11]
The compose config could use a `"type": "wordpress-plugin"` so that  when version controlling the wp-content directory and using composer to control the plugin version, this package gets installed in the wp-content/plugins directory or wherever it is told to.

https://easyengine.io/tutorials/composer-wordpress/add-composer-to-own-themes-plugins/

This is what I have in my composer.json to tell each package where to go.

```
"extra": {
    "installer-paths": {
      "mu-plugins/{$name}": [
        "type:wordpress-muplugin"
      ],
      "plugins/{$name}": [
        "type:wordpress-plugin"
      ]
    }
  },
```

**Comment by claytoncollie** [comment]
If anybody comes across this, I was able to solve it by updating the `repositories` array to include this information.

```
{
      "type": "package",
      "package": {
        "name": "michaelbourne/gravity-forms-zoom-webinar-registration",
        "version": "1.2.0",
        "type": "wordpress-plugin",
        "source": {
          "url": "https://github.com/michaelbourne/gravity-forms-zoom-webinar-registration.git",
          "type": "git",
          "reference": "master"
        }
      }
    }
```

**Comment by michaelbourne** [comment]
Good idea!
