### ISSUE TITLE
Blank API Error

### ISSUE THREAD

**Issue by apos37** [michaelbourne/gravity-forms-zoom-webinar-registration#12]
Hi Michael, I have set up a ton of webinars over the past 3 years using your plugin, and it's very helpful. Thank you! Usually when there is an error with the Zoom API, it displays the error in json format and I can see what the response body is to find out what went wrong. This time it is completely blank. It just says there is an error without actually showing what it is.

![2024-10-04 13_56_34](https://github.com/user-attachments/assets/51525b42-5e89-48ee-9408-0452221a3115)

The GF logs just show:
```
2024-10-04 11:01:18.643095 - ERROR --> Zoom API Error getting Zoom token: Bad Request 
2024-10-04 11:01:18.643268 - ERROR --> GravityZWR::process_feed(): Zoom API error when attempting registration:  
```

There is nothing in my debug logs either.

All of my Zoom Webinar Settings are still showing a green checkmark. It was working fine a couple weeks ago. Any indication why it would get a bad request?

**Comment by michaelbourne** [comment]
Hi @apos37 

Glad you got some use out of it :) I honestly haven't used it in years, it was a covid measure for my agency. 

It looks like the API has changed slightly. I'll update it soon with what I believe is the fix.

**Comment by michaelbourne** [comment]
Want to test the newest push to see if that fixes it for you?

**Comment by apos37** [comment]
Yeah, let me try it.

**Comment by apos37** [comment]
I updated to your new push on v1.3.0, but it still happened. I just got a response from my client that is managing the zoom account, and he said:
```
"I am not sure what is going on with Zoom.
When I go into User Management as the owner I am unable to click on any of the view - edit tabs and I noticed next to the OAuth app it has the following -
OAuth (Soon to be deprecated)"
```

I told him to make sure it's the server-to-server oauth app and gave him the scopes again. Maybe he is using the regular oath and not the server-to-server one. I'll see what he says. Thanks for checking on that so quickly.

**Comment by michaelbourne** [comment]
I just tested on a dev site with a new meeting and 1.3.0 worked for me, so I think it's solved on my end.

**Comment by apos37** [comment]
Great. I'll figure it out on my end then. Thanks!

**Comment by apos37** [comment]
Hi Michael. I found the issue here:
https://github.com/michaelbourne/gravity-forms-zoom-webinar-registration/blob/41801653bebc1211c2bdb6b862cea71fa7b26a9b/includes/class-gravityzwr-zoomapi.php#L41

It is coming up empty for me. So I updated [the function](https://github.com/michaelbourne/gravity-forms-zoom-webinar-registration/blob/41801653bebc1211c2bdb6b862cea71fa7b26a9b/includes/class-gravityzwr.php#L531) on my end like so:

```php
public function get_zoom_settings_keys() {

	$plugin_settings = GFCache::get( 'zwr_plugin_settings' );
	if ( ! $plugin_settings ) {
		$plugin_settings = $this->get_plugin_settings();
	}
	return $plugin_settings;
}
```

And of course it's no longer static, so I updated [the call](https://github.com/michaelbourne/gravity-forms-zoom-webinar-registration/blob/41801653bebc1211c2bdb6b862cea71fa7b26a9b/includes/class-gravityzwr-zoomapi.php#L41) to `$options = (new GravityZWR())->get_zoom_settings_keys();`

Now it works fine. I am not set up to do pull requests on the computer I'm on, so if it's possible to update it on your end that would be great. 👍👍

**Comment by apos37** [comment]
Alternatively, if you are no longer interested in maintaining this project, I'd be happy taking it over, publishing it to the WP repo and giving you credit. I have a few other plugins on there including some Gravity Forms add-ons. I'd contact you directly, but your website contact form is turned off, and I'm not on X.

**Comment by michaelbourne** [comment]
@apos37 I'd be open to that. Just keep me as a contributor for credit if you don't mind, I don't need SVN access though. You can always email me at michael@ursa6.com
