### ISSUE TITLE
Plugin doesn't work after new upgrade

### ISSUE THREAD

**Issue by xaif** [michaelbourne/gravity-forms-zoom-webinar-registration#2]
Hello,

Loved your work and it is amazing. After the upgrade of WordPress and gravity forms the plugin is not working anymore.

**Comment by michaelbourne** [comment]
Hey Xaif,

Can you be more specific? I just tested it on the newest versions of WP and GF, and there were no errors.

The only time I would expect to see an issue is if you select the wrong meeting type on the feed settings on your for, as webinar and meeting have different endpoints.
