### ISSUE TITLE
Select field

### ISSUE THREAD

**Issue by chrtzortzis** [michaelbourne/gravity-forms-zoom-webinar-registration#3]
Hi, very good work! Congratulations!
Is it possible to use SELECT fields in form? It is very useful for Countries.

**Comment by michaelbourne** [comment]
Thanks for the kind words. You should be able to use select fields, yes.

**Comment by chrtzortzis** [comment]
Zoom doesn't seem to take the field value, when we use select field at form. 
Thank you!

**Comment by michaelbourne** [comment]
You will need to choose the new field in the Feed settings for it's
matching Zoom data point.
__________________________________
*Michael Bourne*

**Comment by chrtzortzis** [comment]
At Feed settings doesn't show up the select field that i have made to match it with the zoom data point, but only the texts fields.

**Comment by michaelbourne** [comment]
Ah, you seem to be right on that one. You need to allow select fields to work for the specific merge field type. In this case, address for country.

You can find the array at https://github.com/michaelbourne/gravity-forms-zoom-webinar-registration/blob/master/includes/class-gravityzwr.php#L370

**Comment by chrtzortzis** [comment]
Thank you so much for your support!
